/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaui_bankingsystem;
import java.sql.*;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import design.GlassPanePopup;
import java.awt.*;
import static javaui_bankingsystem.MainFrame.*;
import static javaui_bankingsystem.Message.msgbody;
import static javaui_bankingsystem.Message.msgtitle;
import javax.swing.*;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
/**
 *
 * @author Administrator
 */
public class TransferFunds extends javax.swing.JFrame {

    Image brandIconSVG = new FlatSVGIcon("icon/Brand Logo (NG).svg").getImage();
    ImageIcon closeSVG = new FlatSVGIcon("icon/Close.svg",30,30);
    ImageIcon searchSVG = new FlatSVGIcon("icon/Search_Icon.svg",20,20);
    public TransferFunds() {
        initComponents();
        GlassPanePopup.install(this);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setIconImage(brandIconSVG);
        close.setIcon(closeSVG);
        btnSearch.setIcon(searchSVG);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTransferAccount = new javax.swing.JPanel();
        transferAccount = new javax.swing.JTextField();
        close = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        transferAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        customButton1 = new design.CustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        searchTransferAccount.setBackground(new java.awt.Color(255, 255, 255));
        searchTransferAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        transferAccount.setBorder(null);

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 153, 255));
        jLabel6.setOpaque(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Note: \n        Please input the account you want to transfer to and then input the amount to be \ntransferred. The maximum amount allowed to be transferred is : above 100 and below 10,000\npesos. Thank you for understanding!\n\n                                                                                                                             -management");
        jTextArea1.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("TRANSFER FUNDS");

        jLabel3.setText("Account Number");

        jLabel5.setBackground(new java.awt.Color(0, 153, 255));
        jLabel5.setOpaque(true);

        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 153, 255));
        jLabel7.setOpaque(true);

        transferAmount.setBorder(null);

        jLabel8.setText("Amount to be transferred");

        customButton1.setBackground(new java.awt.Color(0, 153, 255));
        customButton1.setForeground(new java.awt.Color(255, 255, 255));
        customButton1.setText("Confirm");
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchTransferAccountLayout = new javax.swing.GroupLayout(searchTransferAccount);
        searchTransferAccount.setLayout(searchTransferAccountLayout);
        searchTransferAccountLayout.setHorizontalGroup(
            searchTransferAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTransferAccountLayout.createSequentialGroup()
                .addGroup(searchTransferAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchTransferAccountLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchTransferAccountLayout.createSequentialGroup()
                        .addGroup(searchTransferAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchTransferAccountLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(searchTransferAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(searchTransferAccountLayout.createSequentialGroup()
                                        .addComponent(transferAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(transferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(searchTransferAccountLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel4))
                            .addGroup(searchTransferAccountLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchTransferAccountLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(searchTransferAccountLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchTransferAccountLayout.setVerticalGroup(
            searchTransferAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTransferAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchTransferAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchTransferAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchTransferAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        MainFrame mf = new MainFrame();
        mf.show();
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        try{
            //search for the user from the database
            Connection connection = DriverManager.getConnection(database, username, password);
            PreparedStatement statement = connection.prepareStatement("SELECT Name FROM bank_user WHERE Account_Number = ?");
            statement.setString(1, transferAccount.getText());
            ResultSet resultSet = statement.executeQuery();
            resultSet.next();
            JOptionPane.showMessageDialog(this, "The user name is: " + resultSet.getString("Name"));

        }catch (SQLException ex) {
            msgtitle = "NOTICE!";
            msgbody = ("The user doesn't exist in the database");
            GlassPanePopup.showPopup(new Message());
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
        try {
            //gets amount to be transferred from JTextField
            String transferAmt = transferAmount.getText();   
            if (Double.parseDouble(transferAmt) < 10000){
                Connection connection = DriverManager.getConnection(database, username, password);
                PreparedStatement statement = connection.prepareStatement("SELECT Balance FROM bank_user WHERE Account_Number = ?");
                statement.setString(1, transferAccount.getText());
                ResultSet resultSet = statement.executeQuery();
                resultSet.next();
                currentValue = resultSet.getDouble("Balance");

                //calculates new balance for the transferred account
                Double _tempbalance = currentValue + Double.valueOf(transferAmt);

                //updates the database for the transfered account
                PreparedStatement updateStatement = connection.prepareStatement("UPDATE bank_user SET Balance = ? WHERE Account_Number = ?");
                updateStatement.setDouble(1, _tempbalance);
                updateStatement.setString(2, transferAccount.getText());
                updateStatement.executeUpdate();
                
                String sql = "INSERT INTO `" + transferAccount.getText() + "` (`DESCRIPTION`, `AMOUNT`, `BALANCE`) "
                    + "VALUES ('TRANSFER FUNDS', " + transferAmt + ", " + _tempbalance + ")";

                pst.executeUpdate(sql);
                updateDB();
                
                
                try {
                //accesses the balance from the database of the transferee
                connection = DriverManager.getConnection(database, username, password);
                statement = connection.prepareStatement("SELECT Balance FROM bank_user WHERE Account_Number = ?");
                statement.setString(1, value);
                resultSet = statement.executeQuery();
                resultSet.next();
                currentValue = resultSet.getDouble("Balance");

                //calculates new balance of the transferee
                balance = currentValue - Double.valueOf(transferAmt);

                //updates the database of the transferee
                updateStatement = connection.prepareStatement("UPDATE bank_user SET Balance = ? WHERE Account_Number = ?");
                updateStatement.setDouble(1, balance);
                updateStatement.setString(2, value);
                updateStatement.executeUpdate();

                

                
                getBalance();
                disBalance.setText(currentValue.toString());
                
                connection = DriverManager.getConnection(database, username, password);
                statement = connection.prepareStatement("SELECT Name FROM bank_user WHERE Account_Number = ?");
                statement.setString(1, transferAccount.getText());
                resultSet = statement.executeQuery();
                resultSet.next();
                
                // Close the database connection
                connection.close();
                
                //Confirmation Message
                msgtitle = "TRANSACTION COMPLETE!";
                msgbody = ("You have transferred an amount of: ₱ " + transferAmount.getText() + " to " + resultSet.getString("Name")+"! Your current balance is: ₱ "
                        + currentValue +"! \nThank you for using Finance Fox Banking!");
                GlassPanePopup.showPopup(new Message());
            
                transferAmount.setText("");
                
                
            } catch (SQLException ex) {
                
                java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            
            sql = "INSERT INTO `" + value + "` (`DESCRIPTION`, `AMOUNT`, `BALANCE`) "
                    + "VALUES ('TRANSFER FUNDS', " + transferAmt + ", " + balance + ")";
            pst.executeUpdate(sql);
            updateDB();

            // Close the database connection
            connection.close();
        }else{
                msgtitle = "NOTICE!";
                msgbody = ("The amount exceeds the transferable amount");
                GlassPanePopup.showPopup(new Message());
            } 
        }catch (SQLException ex) {
            msgtitle = "NOTICE!";
            msgbody = ("The user doesn't exist in the database");
            GlassPanePopup.showPopup(new Message());
        }
            

            //reducts the amount transferred   
    }//GEN-LAST:event_customButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferFunds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel close;
    private design.CustomButton customButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel searchTransferAccount;
    private javax.swing.JTextField transferAccount;
    private javax.swing.JTextField transferAmount;
    // End of variables declaration//GEN-END:variables
}
